xrange:
  - 500
yrange:
  - 500
xscale:
  - 1.5
yscale:
  - 1.5
xshift:
  - 2
yshift:
  - 2
xzoom:
  - 0.5
yzoom:
  - 0.5
xstretch:
  - 1
ystretch:
  - 1
initial_sharpness:
  - 300
limit1:
  - 4
limit2:
  - 1
contrast:
  - 0.7
enhance1:
  - 2
enhance2:
  - 0.27015